version: "3.7"

networks:
  coingecko:
    driver: "bridge"

services:
  php-cli:
    build:
      dockerfile: docker/Dockerfile
      context: ./..
    volumes:
      - ../:/mnt/app
    networks:
      - coingecko
    links:
      - cg-redis

  cg-redis:
    image: redis:4.0
    container_name: coingecko_redis
    restart: always
    command:
      - 'redis-server'
      - '--loglevel ${REDIS_LOGLEVEL:-warning}'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory ${REDIS_MAXMEM:-50mb}'
    volumes:
      - ./redis/data:/data
    ports:
      - "6382:6380"
    networks:
      - coingecko